### ISSUE TITLE
Error when scanning package with missing optional dependency

### ISSUE THREAD

**Issue by gdereese** [gdereese/abogado#14]
```
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open 'node_modules/fsevents/package.json'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at addDependency (/home/travis/build/gdereese/amigo-server/node_modules/abogado/dist/package-builder.js:8:45)
    at _.forEach (/home/travis/build/gdereese/amigo-server/node_modules/abogado/dist/package-builder.js:30:42)
    at arrayEach (/home/travis/build/gdereese/amigo-server/node_modules/abogado/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/travis/build/gdereese/amigo-server/node_modules/abogado/node_modules/lodash/lodash.js:9359:14)
    at Object.build (/home/travis/build/gdereese/amigo-server/node_modules/abogado/dist/package-builder.js:30:7)
    at Object.run (/home/travis/build/gdereese/amigo-server/node_modules/abogado/dist/processor.js:29:32)
    at Object.<anonymous> (/home/travis/build/gdereese/amigo-server/node_modules/abogado/dist/index.js:16:11)
    at Module._compile (module.js:649:30)
```

**Comment by gdereese** [comment]
I think this should have been addressed by 6bd629b1e918209c6600f999e4e6da9d703e12dc.
